### ISSUE TITLE
Gallium broken in Chrome 66

### ISSUE THREAD

**Issue by jaredlynchart** [sleexyz/gallium#115]

**Comment by sleexyz** [comment]
Can you provide details into how this ended up happening? Did you happen to change any IAC settings?

**Comment by jaredlynchart** [comment]
Hard to say.. just hadn't used it for a few days and I used it again and it wasn't sending any data. I didn't change any midi or driver settings on ableton or on my OS. Michael tried to send data too and couldn't.

**Comment by jaredlynchart** [comment]
Version 66.0.3359.139 (Official Build) (64-bit)
(and yes websynths does send midi to ableton)

**Comment by sleexyz** [comment]
Okay, so the problem is with Chrome 66, perhaps they deprecated an API silently or something.

This is known problem: https://zendrumstudio.com/latest-chrome-breaks-midi-support/

A workaround is to download Chromium 65:
- OSX: https://sourceforge.net/projects/osxportableapps/files/Chromium/
- Windows: https://github.com/RobRich999/Chromium_Clang/tags?after=v66.0.3344.0-r535410-win64
- Linux: Figure it out :p

Fix coming ASAP!

**Comment by sleexyz** [comment]
The issue seems to be with sending timestamps with MIDI Events.

Source: 
- https://zendrumstudio.com/latest-chrome-breaks-midi-support/#comment-116
- https://twitter.com/toyoshim/status/989202339629182976

If timestamps are omitted or are set to `0`, then MIDI Events go through.

Unfortunately we need timestamps since we send events only once per beat, and use timestamps for sub-beat timing.

Investigation to continue. Perhaps Chrome 67 fixes it?

**Comment by sleexyz** [comment]
Chromium bug documented here:
https://bugs.chromium.org/p/chromium/issues/detail?id=835664

Fixed in 66.0.3359.141, apparently should be shipped sometime this week.

**Comment by sleexyz** [comment]
keeping issue open until fix lands

**Comment by sleexyz** [comment]
Fix landed in Chrome Stable

**Comment by jaredlynchart** [comment]
Nice! thanks!
